---
# Source artifacts on the jumpbox
worker_source_directory: /home/vagrant/kubernetes-the-hard-way/downloads
worker_staging_directory: /tmp/kubernetes-lab-worker

# Binary installation
kubernetes_binary_directory: /usr/local/bin

# CNI
cni_binary_directory: /opt/cni/bin
cni_config_directory: /etc/cni/net.d

# containerd
containerd_config_directory: /etc/containerd

# kubelet
kubelet_directory: /var/lib/kubelet

# kube-proxy
kube_proxy_directory: /var/lib/kube-proxy

# Kubernetes component logging
worker_log_level: 2

# Artifact versions
cni_plugins_version: "v1.6.2"
containerd_version: "2.1.0-beta.0"
crictl_version: "v1.32.0"

# Artifact architecture
worker_artifact_arch: "arm64"