---
control_plane_certificates:
  - name: ca.pem
    mode: "0644"

  - name: kubernetes.pem
    mode: "0600"

  - name: kubernetes-key.pem
    mode: "0600"

  - name: kube-controller-manager.pem
    mode: "0600"

  - name: kube-controller-manager-key.pem
    mode: "0600"

  - name: kube-scheduler.pem
    mode: "0600"

  - name: kube-scheduler-key.pem
    mode: "0600"

  - name: service-account.pem
    mode: "0600"

  - name: service-account-key.pem
    mode: "0600"

kubernetes_cert_source_dir: "/home/vagrant/certs"
kubernetes_cert_dest_dir: "/etc/kubernetes/pki"
