---
- name: Stage Kubernetes kubeconfigs from jumpbox
  hosts: jumpbox
  gather_facts: false
  roles:
    - role: kubeconfigs
      kubeconfig_action: stage

- name: Install Kubernetes kubeconfigs
  hosts:
    - control_plane
    - workers
  gather_facts: false
  become: true
  roles:
    - role: kubeconfigs
      kubeconfig_action: install

- name: Clean kubeconfig staging area
  hosts: localhost
  gather_facts: false
  roles:
    - role: kubeconfigs
      kubeconfig_action: cleanup
